import { MicrositeTheme, ShortLink, Microsite, User, AbuseReport, AuditLog, AnalyticsRecord, DeviceStat, ReferrerStat } from '@/types';

export const PREBUILT_THEMES: MicrositeTheme[] = [
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    backgroundType: 'solid',
    background: '#F8FAFC',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subtextColor: '#64748B',
    accentColor: '#5B5BF7',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'solid',
    buttonRadius: 12,
    buttonBg: '#5B5BF7',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'midnight-obsidian',
    name: 'Midnight Obsidian',
    backgroundType: 'gradient',
    background: 'linear-gradient(180deg, #0B0F19 0%, #111827 100%)',
    cardBg: '#1E293B',
    textColor: '#F8FAFC',
    subtextColor: '#94A3B8',
    accentColor: '#38BDF8',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'glass',
    buttonRadius: 14,
    buttonBg: 'rgba(255, 255, 255, 0.08)',
    buttonTextColor: '#F8FAFC',
  },
  {
    id: 'ocean-cyan',
    name: 'Ocean Cyan',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #0F172A 0%, #082F49 50%, #0E7490 100%)',
    cardBg: 'rgba(15, 23, 42, 0.7)',
    textColor: '#FFFFFF',
    subtextColor: '#7DD3FC',
    accentColor: '#06B6D4',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'solid',
    buttonRadius: 16,
    buttonBg: '#06B6D4',
    buttonTextColor: '#0F172A',
  },
  {
    id: 'lavender-glow',
    name: 'Lavender Glow',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #F5F3FF 0%, #EDE9FE 50%, #DDD6FE 100%)',
    cardBg: '#FFFFFF',
    textColor: '#2E1065',
    subtextColor: '#6D28D9',
    accentColor: '#7C3AED',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'solid',
    buttonRadius: 20,
    buttonBg: '#7C3AED',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'warm-sunset',
    name: 'Warm Terracotta',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 100%)',
    cardBg: '#FFFFFF',
    textColor: '#431407',
    subtextColor: '#9A3412',
    accentColor: '#EA580C',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'solid',
    buttonRadius: 14,
    buttonBg: '#EA580C',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'monochrome-slate',
    name: 'Monochrome Clean',
    backgroundType: 'solid',
    background: '#18181B',
    cardBg: '#27272A',
    textColor: '#FAFAFA',
    subtextColor: '#A1A1AA',
    accentColor: '#FFFFFF',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'outline',
    buttonRadius: 9999,
    buttonBg: 'transparent',
    buttonTextColor: '#FAFAFA',
  },
  // ===== TEMA PASTEL LEMBUT (KEHIJAUAN, KEKUNINGAN, KEBIRUAN, KEUNGUAN) =====
  {
    id: 'pastel-sage',
    name: 'Pastel Sage (Kehijauan)',
    backgroundType: 'solid',
    background: '#F0FDF4',
    cardBg: '#FFFFFF',
    textColor: '#14532D',
    subtextColor: '#166534',
    accentColor: '#059669',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 16,
    buttonBg: '#10B981',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'pastel-butter',
    name: 'Pastel Butter (Kekuningan)',
    backgroundType: 'solid',
    background: '#FEFCE8',
    cardBg: '#FFFFFF',
    textColor: '#713F12',
    subtextColor: '#854D0E',
    accentColor: '#D97706',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 20,
    buttonBg: '#F59E0B',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'pastel-sky',
    name: 'Pastel Sky (Kebiruan)',
    backgroundType: 'solid',
    background: '#F0F9FF',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    subtextColor: '#0369A1',
    accentColor: '#0284C7',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 16,
    buttonBg: '#0EA5E9',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'pastel-lilac',
    name: 'Pastel Lilac (Keunguan)',
    backgroundType: 'solid',
    background: '#FAF5FF',
    cardBg: '#FFFFFF',
    textColor: '#581C87',
    subtextColor: '#7E22CE',
    accentColor: '#9333EA',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 20,
    buttonBg: '#A855F7',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'pastel-peach',
    name: 'Pastel Peach (Kemerahan)',
    backgroundType: 'solid',
    background: '#FFF1F2',
    cardBg: '#FFFFFF',
    textColor: '#881337',
    subtextColor: '#BE123C',
    accentColor: '#E11D48',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 16,
    buttonBg: '#F43F5E',
    buttonTextColor: '#FFFFFF',
  },
  // ===== TEMA GRADASI 2 WARNA KEKINIAN =====
  {
    id: 'grad-sunset',
    name: 'Sunset Coral (Gradasi)',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #FF6B6B 0%, #FFA07A 100%)',
    cardBg: '#FFFFFF',
    textColor: '#1E293B',
    subtextColor: '#64748B',
    accentColor: '#FF6B6B',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 9999,
    buttonBg: 'linear-gradient(135deg, #FF6B6B 0%, #FFA07A 100%)',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'grad-aurora',
    name: 'Aurora Cyan (Gradasi)',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #059669 0%, #06B6D4 100%)',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subtextColor: '#0E7490',
    accentColor: '#059669',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 16,
    buttonBg: 'linear-gradient(135deg, #059669 0%, #06B6D4 100%)',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'grad-cosmic',
    name: 'Cosmic Violet (Gradasi)',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #4F46E5 0%, #9333EA 100%)',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subtextColor: '#4338CA',
    accentColor: '#4F46E5',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 20,
    buttonBg: 'linear-gradient(135deg, #4F46E5 0%, #9333EA 100%)',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'grad-ocean',
    name: 'Ocean Sky (Gradasi)',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #0284C7 0%, #38BDF8 100%)',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subtextColor: '#0369A1',
    accentColor: '#0284C7',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 14,
    buttonBg: 'linear-gradient(135deg, #0284C7 0%, #38BDF8 100%)',
    buttonTextColor: '#FFFFFF',
  },
  {
    id: 'grad-amber',
    name: 'Amber Glow (Gradasi)',
    backgroundType: 'gradient',
    background: 'linear-gradient(135deg, #F59E0B 0%, #EA580C 100%)',
    cardBg: '#FFFFFF',
    textColor: '#431407',
    subtextColor: '#9A3412',
    accentColor: '#EA580C',
    fontFamily: 'var(--font-geist-sans), sans-serif',
    buttonVariant: 'liquidglass',
    buttonRadius: 16,
    buttonBg: 'linear-gradient(135deg, #F59E0B 0%, #EA580C 100%)',
    buttonTextColor: '#FFFFFF',
  },
];

export const INITIAL_USER: User = {
  uid: 'usr_alfyarnaim_admin',
  email: 'alfyarnaim@gmail.com',
  emailVerified: true,
  displayName: 'Alfy Arnaim',
  username: 'alfyarnaim',
  photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'SUPER_ADMIN',
  status: 'ACTIVE',
  createdAt: '2026-09-01T08:00:00Z',
  updatedAt: new Date().toISOString(),
  lastLoginAt: new Date().toISOString(),
  shortLinksCount: 0,
  micrositesCount: 0,
};

export const INITIAL_USERS_LIST: User[] = [INITIAL_USER];

// Clean empty initial data (No dummy links or microsites)
export const INITIAL_LINKS: ShortLink[] = [];
export const INITIAL_MICROSITES: Microsite[] = [];

// Khusus Pratinjau Tampilan Visual Ponsel di Beranda (Landing Page Showcase Preview)
export const LANDING_DEMO_MICROSITE: Microsite = {
  id: 'ms_demo_mfyevent',
  ownerId: 'usr_alfyarnaim_admin',
  slug: 'mfyevent',
  title: 'MfyEvent Showcase — Link Hub Resmi',
  status: 'PUBLISHED',
  profile: {
    name: 'MfyEvent 2.0',
    bio: 'Platform Pemendek Tautan Cepat & Builder Microsite Interaktif Masa Depan.',
    avatarUrl: '/icon.png',
    category: 'OFFICIAL SHOWCASE',
    verified: true,
  },
  theme: PREBUILT_THEMES[0], // Minimal Light
  seo: {
    metaTitle: 'MfyEvent 2.0 | Showcase',
    metaDescription: 'Pratinjau tampilan microsite mobile-first modern.',
  },
  createdAt: '2026-09-01T10:00:00Z',
  updatedAt: '2026-09-13T10:00:00Z',
  publishedAt: '2026-09-01T10:00:00Z',
  views: 0,
  uniqueVisitors: 0,
  blocks: [
    {
      id: 'demo_blk_1',
      type: 'HEADING',
      order: 1000,
      visible: true,
      content: {
        title: 'Selamat Datang di MfyEvent',
        level: 'h2',
      },
    },
    {
      id: 'demo_blk_2',
      type: 'LINK',
      order: 2000,
      visible: true,
      content: {
        title: '🚀 Buat Tautan Singkat Gratis Sekarang',
        url: 'https://event.mfytech.my.id',
        description: 'Tautan berkecepatan tinggi dengan custom slug pilihan Anda',
      },
    },
    {
      id: 'demo_blk_3',
      type: 'LINK',
      order: 3000,
      visible: true,
      content: {
        title: '🎨 Bangun Halaman Microsite Anda Sendiri',
        url: 'https://event.mfytech.my.id/register',
        description: 'Desain responsif mobile-first dalam hitungan menit',
      },
    },
    {
      id: 'demo_blk_soc',
      type: 'SOCIAL',
      order: 4000,
      visible: true,
      content: {
        socials: [
          { platform: 'youtube', url: 'https://youtube.com/@mfytech' },
          { platform: 'instagram', url: 'https://instagram.com/mfytech' },
          { platform: 'whatsapp', url: 'https://wa.me/6281234567890' },
        ],
      },
    },
  ],
};

// Clean zero traffic baselines
export const MOCK_TRAFFIC_7D: AnalyticsRecord[] = [
  { date: '07 Sep', clicks: 0, visitors: 0 },
  { date: '08 Sep', clicks: 0, visitors: 0 },
  { date: '09 Sep', clicks: 0, visitors: 0 },
  { date: '10 Sep', clicks: 0, visitors: 0 },
  { date: '11 Sep', clicks: 0, visitors: 0 },
  { date: '12 Sep', clicks: 0, visitors: 0 },
  { date: '13 Sep', clicks: 0, visitors: 0 },
];

export const MOCK_TRAFFIC_14D: AnalyticsRecord[] = [
  { date: '31 Aug', clicks: 0, visitors: 0 },
  { date: '01 Sep', clicks: 0, visitors: 0 },
  { date: '02 Sep', clicks: 0, visitors: 0 },
  { date: '03 Sep', clicks: 0, visitors: 0 },
  { date: '04 Sep', clicks: 0, visitors: 0 },
  { date: '05 Sep', clicks: 0, visitors: 0 },
  { date: '06 Sep', clicks: 0, visitors: 0 },
  { date: '07 Sep', clicks: 0, visitors: 0 },
  { date: '08 Sep', clicks: 0, visitors: 0 },
  { date: '09 Sep', clicks: 0, visitors: 0 },
  { date: '10 Sep', clicks: 0, visitors: 0 },
  { date: '11 Sep', clicks: 0, visitors: 0 },
  { date: '12 Sep', clicks: 0, visitors: 0 },
  { date: '13 Sep', clicks: 0, visitors: 0 },
];

export const MOCK_TRAFFIC_30D: AnalyticsRecord[] = [
  { date: '15 Aug', clicks: 0, visitors: 0 },
  { date: '18 Aug', clicks: 0, visitors: 0 },
  { date: '21 Aug', clicks: 0, visitors: 0 },
  { date: '24 Aug', clicks: 0, visitors: 0 },
  { date: '27 Aug', clicks: 0, visitors: 0 },
  { date: '30 Aug', clicks: 0, visitors: 0 },
  { date: '02 Sep', clicks: 0, visitors: 0 },
  { date: '05 Sep', clicks: 0, visitors: 0 },
  { date: '08 Sep', clicks: 0, visitors: 0 },
  { date: '11 Sep', clicks: 0, visitors: 0 },
  { date: '13 Sep', clicks: 0, visitors: 0 },
];

export const MOCK_TRAFFIC_DATA: AnalyticsRecord[] = MOCK_TRAFFIC_14D;

export const MOCK_DEVICES: DeviceStat[] = [];
export const MOCK_REFERRERS: ReferrerStat[] = [];
export const MOCK_REPORTS: AbuseReport[] = [];
export const MOCK_AUDIT_LOGS: AuditLog[] = [];

